# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b3ed71e915e72a24ca889f27556d438"
name = "hairhouse-discount-functions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
