query DeliveryInput {
  cart {
    cost {
      totalAmount {
        amount
      }
    }
    buyerIdentity {
      customer {
        isPlatinumMember: hasAnyTag(tags: ["Platinum Member"])
      }
    }
    deliveryGroups {
      id
      deliveryOptions {
        handle
        title
        code
        cost {
          amount
        }
      }
    }
  }
  shop {
    localTime {
      date
    }
    promoConfig: metafield(namespace: "$app:promo-config", key: "settings") {
      jsonValue
    }
  }
  discount {
    discountClasses
  }
}
